export default {
  ids: {
    repeatWord: 'repeat-word',
    startGame: 'start-game',
    trainText: 'train-text',
    playText: 'play-text',
    switcher: 'switcher',
    cardsPoint: 'cardsPoint',
    audio: 'audio',
    wordReverse: 'wordReverse',
    questionIcon: 'question-icon',
    playIcon: 'play-icon',
    gameIcon: 'game-icon',
    cardTrain: 'card-train',
    cardPlay: 'card-play',
    starLine: 'starLine',
    menu: 'menu',
    dismisButton: 'dismis-button',
    startGameBtn: 'startGameBtn',
    repeatWordBtn: 'repeatWordBtn',
  },

  classNames: {
    outlineSucess: 'btn-outline-success',
    textDark: 'text-dark',
    textSuccess: 'text-success',
    btnPrimary: '.btn-primary',
    btnSucess: '.btn-success',
    show: 'show',
    active: 'active',
    cardAnimation: '.cards .card_animation',
    col12: '.col-12',
    front: '.front',
    back: '.back',
    card: '.card',
    img: 'img',
    rowCols4: 'row-cols-4',
    rowCols1: 'row-cols-1',
    overlay: '.overlay',
    sidebar: '.sidebar',
    menu: '.menu',
    sidebarList: '.sidebar__list',
    listLinks: '.sidebar__list-li',
    activeLink: '.activeLink',
    audioGame: '.audioGame',
  },

};
